import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Suspense } from "react";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { AuthHeader } from "@/components/auth/auth-header";
import { ClerkAuthBridge } from "@/components/auth/clerk-auth-bridge";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Otherwise root layout can be static; logs only at build time and won’t show in Vercel request logs. */
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const apiOrigin = (process.env.NEXT_PUBLIC_API_BASE_URL ?? "").replace(
    /\/$/,
    "",
  );

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <script
            suppressHydrationWarning
            dangerouslySetInnerHTML={{
              __html: `window.__CAMPAIGN_CENTER_API_ORIGIN__=${JSON.stringify(apiOrigin)};`,
            }}
          />
          <AuthHeader />
          <ClerkAuthBridge>
            <Suspense
              fallback={
                <div className="flex min-h-dvh items-center justify-center bg-[#030712] text-sm text-slate-400">
                  Loading…
                </div>
              }
            >
              {children}
            </Suspense>
          </ClerkAuthBridge>
        </ClerkProvider>
      </body>
    </html>
  );
}
