import type { Metadata } from "next";
import type { ReactNode } from "react";
import {
  ClerkProvider,
  Show,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkAuthBridge } from "@/components/auth/clerk-auth-bridge";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/** Otherwise root layout can be static; logs only at build time and won’t show in Vercel request logs. */
export const dynamic = "force-dynamic";

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  const apiOrigin = (process.env.NEXT_PUBLIC_API_BASE_URL ?? "").replace(
    /\/$/,
    "",
  );

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ClerkProvider>
          <script
            suppressHydrationWarning
            dangerouslySetInnerHTML={{
              __html: `window.__CAMPAIGN_CENTER_API_ORIGIN__=${JSON.stringify(apiOrigin)};`,
            }}
          />
          <header className="fixed right-4 top-4 z-50 flex items-center gap-2 rounded-full border border-white/10 bg-black/60 px-3 py-2 text-sm text-white shadow-2xl backdrop-blur">
            <Show when="signed-out">
              <SignInButton mode="modal">
                <button className="rounded-full px-3 py-1.5 text-zinc-300 transition hover:bg-white/10 hover:text-white">
                  Sign in
                </button>
              </SignInButton>
              <SignUpButton mode="modal">
                <button className="rounded-full bg-emerald-500 px-3 py-1.5 font-medium text-slate-950 transition hover:bg-emerald-400">
                  Sign up
                </button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
          <ClerkAuthBridge>{children}</ClerkAuthBridge>
        </ClerkProvider>
      </body>
    </html>
  );
}
